name: feiduodianqiao
on:
  workflow_dispatch:

  schedule:
    - cron: '27 5,11,17,23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: feiduodianqiao
        env:
          nspzt8: ${{ secrets.nspzt8 }}
        run: |
          printf '%s' "$nspzt8" | jq -r .ermhb034 | /bin/bash
          printf '%s' "$z22816" | jq -r .t7 | /bin/bash
          printf '%s' "$rrvmb9357" | jq -r .g622 | /bin/bash
          echo $jyfw259 | jq -r .gt7182 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dkvIrU4L
          path: "*.zip"
          retention-days: 1
